//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEAM13SEP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GOPY
    {
        public int ID { get; set; }
        public string GOPY_CODE { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Tiêu đề góp ý không được bỏ trống")]
        public string GOPY_TEN { get; set; }
        public int CHUDE_ID { get; set; }
        public Nullable<int> ADMIN_ID { get; set; }
        public Nullable<int> nutLIKE { get; set; }
       
        public Nullable<int> SINHVIEN_ID { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Nội dung góp ý không được bỏ trống")]
        public string NOIDUNG_GOPY { get; set; }
        public string TRALOI_GOPY { get; set; }
        public Nullable<int> GOPY_STATUS { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    
        public virtual ADMIN ADMIN { get; set; }
        public virtual CHUDE CHUDE { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
        public virtual TRANGTHAI TRANGTHAI { get; set; }
    }
}
