//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEAM13SEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOPY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GOPY()
        {
            this.THONGKEs = new HashSet<THONGKE>();
        }
    
        public int ID { get; set; }
        public string GOPY_CODE { get; set; }
        public string GOPY_TEN { get; set; }
        public Nullable<int> CHUDE_ID { get; set; }
        public Nullable<int> ADMIN_ID { get; set; }
        public Nullable<int> LIKE_ID { get; set; }
        public Nullable<int> SINHVIEN_ID { get; set; }
        public string NOIDUNG { get; set; }
        public string TRALOI { get; set; }
        public string IMAGE_URL { get; set; }
    
        public virtual CHUDE CHUDE { get; set; }
        public virtual USER USER { get; set; }
        public virtual LIKE LIKE { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THONGKE> THONGKEs { get; set; }
    }
}
