//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEAM13SEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGKE
    {
        public int ID { get; set; }
        public Nullable<int> CHUDE_ID { get; set; }
        public Nullable<int> LIKE_ID { get; set; }
        public Nullable<int> GOPY_ID { get; set; }
    
        public virtual CHUDE CHUDE { get; set; }
        public virtual GOPY GOPY { get; set; }
        public virtual LIKE LIKE { get; set; }
    }
}
